spring:
  application:
    name: ctrlgym
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://nkwsihnvnyduumdbopuf.supabase.co/auth/v1
  messages:
    basename: messages/messages
    fallback-to-system-locale: false
    encoding: UTF-8
server:
  port: 80

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  whsec-connected-account: ${STRIPE_WEBHOOK_SECRET_CONNECTED_ACCOUNT}
  whsec-account: ${STRIPE_WEBHOOK_SECRET}

qr:
  jwt-secret: "tu-clave-secreta-muy-larga-de-al-menos-256-bits-aqui"
  expiration-seconds: 10
