spring:
  application:
    name: ctrlgym
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.nkwsihnvnyduumdbopuf
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


server:
  port: 8080
