

-- DROP TYPE public.expense_frequency;

CREATE TYPE public.expense_frequency AS ENUM (
    'ONE_TIME',
    'RECURRING');

-- DROP TYPE public.expense_nature;

CREATE TYPE public.expense_nature AS ENUM (
    'FIXED',
    'VARIABLE');

-- DROP TYPE public.expense_status;

CREATE TYPE public.expense_status AS ENUM (
    'ACTIVE',
    'INACTIVE');

-- DROP TYPE public.invoice_status;

CREATE TYPE public.invoice_status AS ENUM (
    'OPEN',
    'PROCESSING',
    'PAID',
    'FAILED');

-- DROP TYPE public.member_status;

CREATE TYPE public.member_status AS ENUM (
    'AUTH',
    'MEMBER',
    'CUSTOMER');

-- DROP TYPE public.muscle_group;

CREATE TYPE public.muscle_group AS ENUM (
    'CHEST',
    'BACK',
    'BICEPS',
    'TRICEPS',
    'FOREARMS',
    'ABS',
    'QUADRICEPS',
    'HAMSTRINGS',
    'GLUTES',
    'CALVES',
    'HIP_FLEXORS',
    'DELTOID');

-- DROP TYPE public.payment_status;

CREATE TYPE public.payment_status AS ENUM (
    'PROCESSING',
    'PAID',
    'FAILED');

-- DROP TYPE public.recurrence_period;

CREATE TYPE public.recurrence_period AS ENUM (
    'DAILY',
    'WEEKLY',
    'MONTHLY',
    'YEARLY');

-- DROP TYPE public.workout_status;

CREATE TYPE public.workout_status AS ENUM (
    'IN_PROGRESS',
    'COMPLETED',
    'ABANDONED');

-- DROP SEQUENCE access_events_id_seq;

CREATE SEQUENCE access_events_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE device_heartbeat_id_seq;

CREATE SEQUENCE device_heartbeat_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE exercises_id_seq;

CREATE SEQUENCE exercises_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE expense_occurrences_id_seq;

CREATE SEQUENCE expense_occurrences_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE expenses_id_seq;

CREATE SEQUENCE expenses_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE machines_id_seq;

CREATE SEQUENCE machines_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE membership_cancellation_reason_id_seq;

CREATE SEQUENCE membership_cancellation_reason_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE memberships_id_seq;

CREATE SEQUENCE memberships_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE routine_executions_id_seq;

CREATE SEQUENCE routine_executions_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE routines_id_seq;

CREATE SEQUENCE routines_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    START 1
    CACHE 1
    NO CYCLE;
-- public.expense_categories definition

-- Drop table

-- DROP TABLE expense_categories;

CREATE TABLE expense_categories
(
    id         int4                    NOT NULL,
    code       varchar(100)            NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    is_active  bool      DEFAULT true  NOT NULL,
    CONSTRAINT expense_categories_pkey PRIMARY KEY (id)
);


-- public.gyms definition

-- Drop table

-- DROP TABLE gyms;

CREATE TABLE gyms
(
    id                int4        NOT NULL,
    name              varchar(50) NOT NULL,
    verifacti_api_key text        NOT NULL,
    stripe_account_id text        NULL,
    CONSTRAINT gyms_pkey PRIMARY KEY (id),
    CONSTRAINT gyms_stripe_account_id_uk UNIQUE (stripe_account_id),
    CONSTRAINT gyms_verifacti_api_key_uk UNIQUE (verifacti_api_key)
);


-- public.invoice_counter definition

-- Drop table

-- DROP TABLE invoice_counter;

CREATE TABLE invoice_counter
(
    gym_id      int4           NOT NULL,
    series      varchar(20)    NOT NULL,
    last_number int4 DEFAULT 1 NOT NULL,
    CONSTRAINT invoice_counter_pkey PRIMARY KEY (gym_id, series)
);


-- public.membership_cancellation_reasons definition

-- Drop table

-- DROP TABLE membership_cancellation_reasons;

CREATE TABLE membership_cancellation_reasons
(
    id         int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    code       varchar(50)                                                                                                     NOT NULL,
    sort_order int4                                                                                                            NOT NULL,
    active     bool      DEFAULT true                                                                                          NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP                                                                             NOT NULL,
    CONSTRAINT membership_cancellation_reason_code_key UNIQUE (code),
    CONSTRAINT membership_cancellation_reason_pkey PRIMARY KEY (id)
);


-- public.routine_day_exercise_sets definition

-- Drop table

-- DROP TABLE routine_day_exercise_sets;

CREATE TABLE routine_day_exercise_sets
(
    routine_id  int4 NOT NULL,
    day_number  int4 NOT NULL,
    exercise_id int4 NOT NULL,
    "set"       int2 NOT NULL,
    reps        int2 NOT NULL,
    CONSTRAINT routine_day_exercise_set_pkey PRIMARY KEY (routine_id, day_number, exercise_id, set),
    CONSTRAINT routine_day_exercises_reps_check CHECK ((reps >= 1)),
    CONSTRAINT routine_day_exercises_sets_check CHECK ((set >= 1))
);


-- public.exercises definition

-- Drop table

-- DROP TABLE exercises;

CREATE TABLE exercises
(
    id           int4 GENERATED ALWAYS AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    name         varchar(100)                                                                                                NOT NULL,
    description  text                                                                                                        NULL,
    muscle_group public.muscle_group                                                                                         NOT NULL,
    image        text                                                                                                        NULL,
    gym_id       int4                                                                                                        NOT NULL,
    CONSTRAINT exercises_pkey PRIMARY KEY (id),
    CONSTRAINT exercises_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES gyms (id)
);


-- public.expense_category_translations definition

-- Drop table

-- DROP TABLE expense_category_translations;

CREATE TABLE expense_category_translations
(
    expense_category_id int4         NOT NULL,
    language_code       varchar(10)  NOT NULL,
    name                varchar(100) NOT NULL,
    description         text         NULL,
    CONSTRAINT expense_category_translations_pkey PRIMARY KEY (expense_category_id, language_code),
    CONSTRAINT expense_category_translations_expense_category_id_fkey FOREIGN KEY (expense_category_id) REFERENCES expense_categories (id)
);


-- public.gym_branches definition

-- Drop table

-- DROP TABLE gym_branches;

CREATE TABLE gym_branches
(
    id              int4              NOT NULL,
    gym_id          int4              NOT NULL,
    name            varchar(50)       NOT NULL,
    is_active       bool DEFAULT true NULL,
    capacity        int2              NULL,
    peak_hour_start time              NULL,
    peak_hour_end   time              NULL,
    CONSTRAINT gyms_pkey1 PRIMARY KEY (id),
    CONSTRAINT gyms_company_id_fkey FOREIGN KEY (gym_id) REFERENCES gyms (id)
);


-- public.machines definition

-- Drop table

-- DROP TABLE machines;

CREATE TABLE machines
(
    id           int4 GENERATED ALWAYS AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    gym_id       int4                                                                                                        NOT NULL,
    gym_branches _int4                                                                                                       NULL,
    all_branches bool                                                                                                        NOT NULL,
    name         varchar(100)                                                                                                NOT NULL,
    description  text                                                                                                        NULL,
    muscle_group public.muscle_group                                                                                         NOT NULL,
    CONSTRAINT chk_all_branches CHECK (((NOT all_branches) OR (gym_branches IS NULL))),
    CONSTRAINT machines_pkey PRIMARY KEY (id),
    CONSTRAINT machines_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES gyms (id)
);


-- public.members definition

-- Drop table

-- DROP TABLE members;

CREATE TABLE members
(
    id                       uuid                 NOT NULL,
    gym_id                   int4                 NOT NULL,
    email                    text                 NULL,
    name                     varchar(20)          NOT NULL,
    first_surname            varchar(20)          NULL,
    second_surname           varchar(20)          NULL,
    avatar_url               text                 NULL,
    gender                   bpchar(1)            NOT NULL,
    birth_date               date                 NULL,
    postal_code              int4                 NULL,
    created_at               timestamptz DEFAULT now() NULL,
    stripe_customer_id       text                 NULL,
    stripe_payment_method_id text                 NULL,
    nif                      varchar(20)          NULL,
    street                   varchar(80)          NULL,
    city                     varchar(30)          NULL,
    state                    varchar(30)          NULL,
    country                  varchar(30)          NULL,
    status                   public.member_status NOT NULL,
    CONSTRAINT members_gender_check CHECK ((gender = ANY (ARRAY ['M'::bpchar, 'F'::bpchar, 'P'::bpchar]))),
    CONSTRAINT members_pkey PRIMARY KEY (id, gym_id),
    CONSTRAINT members_stripe_customer_id_uk UNIQUE (stripe_customer_id),
    CONSTRAINT members_stripe_payment_method_id_uk UNIQUE (stripe_payment_method_id),
    CONSTRAINT members_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES gyms (id)
);


-- public.membership_cancellation_reason_translations definition

-- Drop table

-- DROP TABLE membership_cancellation_reason_translations;

CREATE TABLE membership_cancellation_reason_translations
(
    cancellation_reason_id int4         NOT NULL,
    language_code          varchar(10)  NOT NULL,
    name                   varchar(100) NOT NULL,
    description            text         NULL,
    CONSTRAINT membership_cancellation_reason_translation_pkey PRIMARY KEY (cancellation_reason_id, language_code),
    CONSTRAINT membership_cancellation_reason_tran_cancellation_reason_id_fkey FOREIGN KEY (cancellation_reason_id) REFERENCES membership_cancellation_reasons (id)
);


-- public.membership_plan_branches definition

-- Drop table

-- DROP TABLE membership_plan_branches;

CREATE TABLE membership_plan_branches
(
    membership_plan_id text NOT NULL,
    branch_id          int4 NOT NULL,
    CONSTRAINT membership_plan_branch_pkey PRIMARY KEY (membership_plan_id, branch_id),
    CONSTRAINT membership_plan_branch_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES gym_branches (id)
);


-- public.membership_plans definition

-- Drop table

-- DROP TABLE membership_plans;

CREATE TABLE membership_plans
(
    id              text                      NOT NULL,
    gym_id          int4                      NOT NULL,
    name            varchar(100)              NOT NULL,
    price           numeric(10, 2)            NOT NULL,
    billing_period  varchar(20)               NOT NULL,
    active          bool DEFAULT true         NOT NULL,
    created_at      date DEFAULT CURRENT_DATE NOT NULL,
    stripe_price_id text                      NOT NULL,
    deleted_at      date                      NULL,
    CONSTRAINT membership_plan_billing_period_check CHECK (((billing_period)::text = ANY
        ((ARRAY ['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'SEMESTERLY'::character varying, 'YEARLY'::character varying])::text[]))),
    CONSTRAINT membership_plan_pkey PRIMARY KEY (id),
    CONSTRAINT membership_plans_stripe_price_id_uk UNIQUE (stripe_price_id),
    CONSTRAINT membership_plan_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES gyms (id)
);


-- public.memberships definition

-- Drop table

-- DROP TABLE memberships;

CREATE TABLE memberships
(
    id                     int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    member_id              uuid                                                                                                                     NOT NULL,
    gym_id                 int4                                                                                                                     NOT NULL,
    membership_plan_id     text                                                                                                                     NOT NULL,
    start_date             date                                                                                                                     NOT NULL,
    end_date               date                                                                                                                     NULL,
    next_billing_date      date                                                                                                                     NULL,
    auto_renew             bool DEFAULT true                                                                                                        NOT NULL,
    cancellation_reason_id int4                                                                                                                     NULL,
    stripe_subscription_id text                                                                                                                     NULL,
    CONSTRAINT membership_pkey PRIMARY KEY (id),
    CONSTRAINT memberships_stripe_subscription_id_uk UNIQUE (stripe_subscription_id),
    CONSTRAINT memberships_member_fk FOREIGN KEY (member_id, gym_id) REFERENCES members (id, gym_id)
);


-- public."routines" definition

-- Drop table

-- DROP TABLE "routines";

CREATE TABLE "routines"
(
    id          int4 GENERATED ALWAYS AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    member_id   uuid                                                                                                        NULL,
    gym_id      int4                                                                                                        NULL,
    name        varchar(100)                                                                                                NOT NULL,
    description text                                                                                                        NULL,
    created_at  timestamp DEFAULT now()                                                                                     NOT NULL,
    deleted_at  date                                                                                                        NULL,
    CONSTRAINT routines_pkey PRIMARY KEY (id),
    CONSTRAINT routines_gym_id_fkey FOREIGN KEY (gym_id) REFERENCES gyms (id),
    CONSTRAINT routines_member_fk FOREIGN KEY (member_id, gym_id) REFERENCES members (id, gym_id)
);


-- public.expenses definition

-- Drop table

-- DROP TABLE expenses;

CREATE TABLE expenses
(
    id                bigserial                                              NOT NULL,
    gym_branch_id     int4                                                   NOT NULL,
    category_id       int2                                                   NOT NULL,
    nature            public.expense_nature                                  NOT NULL,
    frequency         public.expense_frequency                               NOT NULL,
    recurrence_period public.recurrence_period                               NULL,
    expected_amount   numeric(12, 2)                                         NULL,
    currency_code     bpchar(3)             DEFAULT 'EUR'::bpchar            NOT NULL,
    start_date        date                                                   NOT NULL,
    end_date          date                                                   NULL,
    status            public.expense_status DEFAULT 'ACTIVE'::expense_status NOT NULL,
    created_at        timestamp             DEFAULT now()                    NOT NULL,
    updated_at        timestamp             DEFAULT now()                    NOT NULL,
    CONSTRAINT chk_expected_amount CHECK (((expected_amount IS NULL) OR (expected_amount >= (0)::numeric))),
    CONSTRAINT chk_recurrence_period CHECK ((
        ((frequency = 'RECURRING'::expense_frequency) AND (recurrence_period IS NOT NULL)) OR
        ((frequency = 'ONE_TIME'::expense_frequency) AND (recurrence_period IS NULL)))),
    CONSTRAINT expenses_pkey PRIMARY KEY (id),
    CONSTRAINT expenses_category_id_fkey FOREIGN KEY (category_id) REFERENCES expense_categories (id),
    CONSTRAINT expenses_gym_branch_id_fkey FOREIGN KEY (gym_branch_id) REFERENCES gym_branches (id)
);


-- public.gym_branch_current_occupancy definition

-- Drop table

-- DROP TABLE gym_branch_current_occupancy;

CREATE TABLE gym_branch_current_occupancy
(
    gym_branch_id int4           NOT NULL,
    count         int2 DEFAULT 0 NOT NULL,
    CONSTRAINT gym_current_occupancy_pkey PRIMARY KEY (gym_branch_id),
    CONSTRAINT gym_current_occupancy_gym_id_fkey FOREIGN KEY (gym_branch_id) REFERENCES gym_branches (id)
);


-- public.gym_branch_heartbeat definition

-- Drop table

-- DROP TABLE gym_branch_heartbeat;

CREATE TABLE gym_branch_heartbeat
(
    id             int8        DEFAULT nextval('device_heartbeat_id_seq'::regclass) NOT NULL,
    gym_branch_id  int4                                                             NOT NULL,
    created_at     timestamptz                                                      NOT NULL,
    received_at    timestamptz DEFAULT now()                                        NOT NULL,
    hostname       varchar(255)                                                     NULL,
    ip             varchar(64)                                                      NULL,
    platform       varchar(255)                                                     NULL,
    python_version varchar(50)                                                      NULL,
    app_version    varchar(50)                                                      NULL,
    cpu_percent    numeric(5, 2)                                                    NULL,
    memory_percent numeric(5, 2)                                                    NULL,
    disk_percent   numeric(5, 2)                                                    NULL,
    temperature_c  numeric(5, 2)                                                    NULL,
    sqlite_ok      bool                                                             NULL,
    pending_events int4        DEFAULT 0                                            NULL,
    CONSTRAINT chk_cpu_percent CHECK (((cpu_percent >= (0)::numeric) AND (cpu_percent <= (100)::numeric))),
    CONSTRAINT chk_disk_percent CHECK (((disk_percent >= (0)::numeric) AND (disk_percent <= (100)::numeric))),
    CONSTRAINT chk_memory_percent CHECK (((memory_percent >= (0)::numeric) AND (memory_percent <= (100)::numeric))),
    CONSTRAINT device_heartbeat_pkey PRIMARY KEY (id),
    CONSTRAINT gym_heartbeat_gyms_fk FOREIGN KEY (gym_branch_id) REFERENCES gym_branches (id)
);


-- public.gym_branch_occupancy_snapshot definition

-- Drop table

-- DROP TABLE gym_branch_occupancy_snapshot;

CREATE TABLE gym_branch_occupancy_snapshot
(
    gym_branch_id int4      NOT NULL,
    snapshot_time timestamp NOT NULL,
    count         int4      NOT NULL,
    CONSTRAINT gym_occupancy_snapshot_pkey PRIMARY KEY (gym_branch_id, snapshot_time),
    CONSTRAINT gym_occupancy_snapshot_gym_id_fkey FOREIGN KEY (gym_branch_id) REFERENCES gym_branches (id)
);


-- public.invoices definition

-- Drop table

-- DROP TABLE invoices;

CREATE TABLE invoices
(
    id                    varchar(100)                             NOT NULL,
    gym_id                int4                                     NOT NULL,
    member_id             uuid                                     NOT NULL,
    series                varchar(20)                              NOT NULL,
    "number"              varchar(20)                              NOT NULL,
    issue_at              date                                     NOT NULL,
    due_at                date                                     NOT NULL,
    status                public.invoice_status                    NOT NULL,
    subtotal              numeric(10, 2)                           NOT NULL,
    tax                   numeric(10, 2) DEFAULT 0                 NOT NULL,
    total                 numeric(10, 2)                           NOT NULL,
    currency              bpchar(3)      DEFAULT 'EUR'::bpchar     NOT NULL,
    created_at            timestamptz    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at            timestamptz    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    stripe_invoice_number varchar(50)                              NOT NULL,
    verifactu_id          uuid                                     NULL,
    CONSTRAINT inoices_serie_number_uk UNIQUE (series, number),
    CONSTRAINT invoices_invoice_number_key UNIQUE (stripe_invoice_number),
    CONSTRAINT invoices_pkey PRIMARY KEY (id),
    CONSTRAINT invoices_verifactu_uk UNIQUE (verifactu_id),
    CONSTRAINT invoices_member_fk FOREIGN KEY (member_id, gym_id) REFERENCES members (id, gym_id)
);
CREATE INDEX idx_invoice_gym ON public.invoices USING btree (gym_id);
CREATE INDEX idx_invoice_member ON public.invoices USING btree (member_id);


-- public.member_accesses definition

-- Drop table

-- DROP TABLE member_accesses;

CREATE TABLE member_accesses
(
    id            int4 GENERATED ALWAYS AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    gym_branch_id int4                                                                                                        NOT NULL,
    member_id     uuid                                                                                                        NOT NULL,
    direction     int4                                                                                                        NOT NULL,
    created_at    timestamptz                                                                                                 NOT NULL,
    received_at   timestamptz DEFAULT now()                                                                                   NOT NULL,
    gym_id        int4                                                                                                        NOT NULL,
    CONSTRAINT access_events_pkey PRIMARY KEY (id),
    CONSTRAINT check_direction CHECK ((direction = ANY (ARRAY [0, 1]))),
    CONSTRAINT access_events_gyms_fk FOREIGN KEY (gym_branch_id) REFERENCES gym_branches (id),
    CONSTRAINT member_accesses_member_fk FOREIGN KEY (member_id, gym_id) REFERENCES members (id, gym_id)
);



-- public.routine_days definition

-- Drop table

-- DROP TABLE routine_days;

CREATE TABLE routine_days
(
    routine_id int4         NOT NULL,
    day_number int2         NOT NULL,
    name       varchar(100) NULL,
    CONSTRAINT routine_day_day_number_check CHECK (((day_number >= 1) AND (day_number <= 7))),
    CONSTRAINT routine_day_pkey PRIMARY KEY (routine_id, day_number),
    CONSTRAINT routine_day_routine_id_fkey FOREIGN KEY (routine_id) REFERENCES "routines" (id) ON DELETE CASCADE
);


-- public.workouts definition

-- Drop table

-- DROP TABLE workouts;

CREATE TABLE workouts
(
    id          int4 GENERATED ALWAYS AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    routine_id  int4                                                                                                        NOT NULL,
    day_number  int2                                                                                                        NOT NULL,
    started_at  timestamptz DEFAULT now()                                                                                   NOT NULL,
    finished_at timestamptz                                                                                                 NULL,
    status      public.workout_status                                                                                       NOT NULL,
    member_id   uuid                                                                                                        NOT NULL,
    CONSTRAINT routine_executions_pkey PRIMARY KEY (id),
    CONSTRAINT routine_executions_routine_days_fk FOREIGN KEY (routine_id, day_number) REFERENCES routine_days (routine_id, day_number)
);


-- public.expense_occurrences definition

-- Drop table

-- DROP TABLE expense_occurrences;

CREATE TABLE expense_occurrences
(
    id                bigserial               NOT NULL,
    expense_id        int8                    NOT NULL,
    occurrence_date   date                    NOT NULL,
    amount            numeric(12, 2)          NOT NULL,
    notes             text                    NULL,
    invoice_reference varchar(100)            NULL,
    created_at        timestamp DEFAULT now() NOT NULL,
    CONSTRAINT chk_occurrence_amount CHECK ((amount >= (0)::numeric)),
    CONSTRAINT expense_occurrences_pkey PRIMARY KEY (id),
    CONSTRAINT expense_occurrences_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES expenses (id)
);


-- public.routine_day_exercises definition

-- Drop table

-- DROP TABLE routine_day_exercises;

CREATE TABLE routine_day_exercises
(
    routine_id   int4          NOT NULL,
    day_number   int4          NOT NULL,
    exercise_id  int4          NOT NULL,
    "position"   int2          NOT NULL,
    rest_seconds numeric(5, 1) NULL,
    CONSTRAINT routine_day_exercises_pkey PRIMARY KEY (routine_id, day_number, exercise_id),
    CONSTRAINT routine_day_exercises_position_check CHECK (("position" >= 1)),
    CONSTRAINT routine_day_exercises_exercise_fk FOREIGN KEY (exercise_id) REFERENCES exercises (id) ON DELETE CASCADE,
    CONSTRAINT routine_day_exercises_routine_day_fk FOREIGN KEY (routine_id, day_number) REFERENCES routine_days (routine_id, day_number) ON DELETE CASCADE
);


-- public.workout_sets definition

-- Drop table

-- DROP TABLE workout_sets;

CREATE TABLE workout_sets
(
    workout_id  int4 NOT NULL,
    exercise_id int4 NOT NULL,
    "set"       int2 NOT NULL,
    reps        int2 NOT NULL,
    CONSTRAINT routine_day_exercise_executions_pkey PRIMARY KEY (workout_id, exercise_id, set),
    CONSTRAINT routine_day_exercise_executions_reps_check CHECK ((reps >= 1)),
    CONSTRAINT routine_day_exercise_executions_set_check CHECK ((set >= 1)),
    CONSTRAINT routine_day_exercise_executions_routine_execution_id_fkey FOREIGN KEY (workout_id) REFERENCES workouts (id)
);


-- DROP FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path TO 'public'
AS
$function$
BEGIN
INSERT INTO public.members (id,
                            gym_id,
                            email,
                            name,
                            first_surname,
                            second_surname,
                            gender,
                            status)
VALUES (NEW.id,
        (NEW.raw_user_meta_data ->> 'gym_id')::int4,
        NEW.email,
        NEW.raw_user_meta_data ->> 'name',
        NEW.raw_user_meta_data ->> 'first_surname',
        NEW.raw_user_meta_data ->> 'second_surname',
        (NEW.raw_user_meta_data ->> 'gender')::bpchar,
        'AUTH');

RETURN NEW;
END;
$function$
;

-- DROP FUNCTION public.update_gym_branch_current_occupancy();

CREATE OR REPLACE FUNCTION public.update_gym_branch_current_occupancy()
    RETURNS trigger
    LANGUAGE plpgsql
AS
$function$
BEGIN

UPDATE gym_branch_current_occupancy
SET count =
        CASE
            WHEN NEW.direction = 0
                THEN count + 1
            WHEN NEW.direction = 1
                THEN GREATEST(count - 1, 0)
            END
WHERE gym_branch_id = NEW.gym_branch_id;

RETURN NEW;

END;
$function$
;

-- Table Triggers

create trigger trg_update_gym_current_occupancy
    after
        insert
    on
        public.member_accesses
    for each row
    execute function update_gym_branch_current_occupancy();
